/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  DemoBarComponent as ODemoBar
} from './components/o-demo-bar/o-demo-bar';

declare global {
  interface HTMLODemoBarElement extends ODemoBar, HTMLElement {
  }
  var HTMLODemoBarElement: {
    prototype: HTMLODemoBarElement;
    new (): HTMLODemoBarElement;
  };
  interface HTMLElementTagNameMap {
    "o-demo-bar": HTMLODemoBarElement;
  }
  interface ElementTagNameMap {
    "o-demo-bar": HTMLODemoBarElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "o-demo-bar": JSXElements.ODemoBarAttributes;
    }
  }
  namespace JSXElements {
    export interface ODemoBarAttributes extends HTMLAttributes {
      events?: string[];
      name?: string;
      pattern?: boolean;
    }
  }
}

